create table if not exists public.drift_metrics (
  metric_id bigint generated by default as identity primary key,
  evaluated_at timestamptz not null default now(),
  prediction_batch_at timestamptz,
  accuracy numeric,
  wape numeric,
  matched_predictions integer not null default 0,
  threshold numeric not null,
  drift_detected boolean not null default false,
  retrained boolean not null default false,
  status text not null default 'ok',
  details jsonb not null default '{}'::jsonb
);

create index if not exists drift_metrics_evaluated_at_idx
  on public.drift_metrics (evaluated_at desc);

alter table public.drift_metrics enable row level security;
